const String supabaseUrl = 'https://jdgqsodglxuazxihhqgq.supabase.co';
const String supabaseAnonKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZ3Fzb2RnbHh1YXp4aWhocWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwODU4ODUsImV4cCI6MjA5MTY2MTg4NX0.3Z2FbXxFewH8zCkeFbA29jzf0tdbbkVUxiFQmiRre_I';
